### ISSUE TITLE
Calling ForeignKeyLoader.for(*args).load with an array of length 1

### ISSUE THREAD

**Issue by farisj** [rmosolgo/graphql-batch-example#2]
I am working on an application that implements a `ForeignKeyLoader` similar to the one you have written in `good_schema/foreign_key_loader.rb`

However, I noticed that when this loader is used in your `schema.rb`, you call it as such:

`ForeignKeyLoader.for(MTG::Card, :expansion_id).load([obj.id])`

Is there an advantage to wrapping `obj.id` in an array? I see that the `ForeignKeyLoader` breaks if these are not present due to the line:

`matching_records = records.select { |r| foreign_value_set.include?(r.send(@foreign_key)) }`

in the loader.

If we change the `.include?` to `==`, the array is no longer needed. Is there another advantage to wrapping the argument in an array that I may not be seeing?

Thanks!

**Comment by rmosolgo** [comment]
:thinking: I can't think of a reason I did it that way. Maybe it was left over from a previous refactor or copy-paste ... or maybe just an oopsie 😆

**Comment by farisj** [comment]
Good to know, thanks! I am just glad I wasn't missing anything hehe. Thanks for your help!
